// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCshmDlhYLMnng-qxkY_GzlfL5ASZ7auY',
    appId: '1:232326417785:web:3c0b3e9943da34ac77f3a8',
    messagingSenderId: '232326417785',
    projectId: 'vegetables-1bbbe',
    authDomain: 'vegetables-1bbbe.firebaseapp.com',
    storageBucket: 'vegetables-1bbbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2VpSweS9ke0k7LNFfPwlBkP3SQF0v0XM',
    appId: '1:232326417785:android:d7a9083b6334561e77f3a8',
    messagingSenderId: '232326417785',
    projectId: 'vegetables-1bbbe',
    storageBucket: 'vegetables-1bbbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_J9gm4ni3kuermmnoXfRLUSdN-93jGPo',
    appId: '1:232326417785:ios:8369156ab0fa4f4377f3a8',
    messagingSenderId: '232326417785',
    projectId: 'vegetables-1bbbe',
    storageBucket: 'vegetables-1bbbe.appspot.com',
    iosBundleId: 'com.aruna.tarkari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_J9gm4ni3kuermmnoXfRLUSdN-93jGPo',
    appId: '1:232326417785:ios:58699ad0d641d21977f3a8',
    messagingSenderId: '232326417785',
    projectId: 'vegetables-1bbbe',
    storageBucket: 'vegetables-1bbbe.appspot.com',
    iosBundleId: 'com.example.newtarkari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCshmDlhYLMnng-qxkY_GzlfL5ASZ7auY',
    appId: '1:232326417785:web:4a1d85e662725c1c77f3a8',
    messagingSenderId: '232326417785',
    projectId: 'vegetables-1bbbe',
    authDomain: 'vegetables-1bbbe.firebaseapp.com',
    storageBucket: 'vegetables-1bbbe.appspot.com',
  );
}
